<?php

/**
 * @file
 * Add a semi-transparent overlay to a page
 */

/**
 * Implements hook_menu().
 */
function toggle_overlay_menu() {
  $items = array();

  $items['admin/config/development/overlay'] = array(
    'title' => 'Toggle Overlay',
    'description' => 'Configure Overlay Images',
    'route_name' => 'toggle_overlay.settings',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['toggle_overlays'] = array(
    'title' => 'Overlay JSON Data',
    'route_name' => 'toggle_overlay.json',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_page_attachments
 */
function toggle_overlay_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'toggle_overlay/toggle-overlay';
}

/**
 * Page Callback: Get Toggle Overlay JSON Data
 *
 * @see toggle_overlay_menu
 */
function _toggle_overlay_get_json() {
  $settings = variable_get('toggle_overlay_pages');

  for ($i = 1; $i <= count($settings); $i++) {
    $file = file_load( $settings[$i]['overlay'] );
    $settings[$i]['overlay'] = file_create_url($file->uri);
  }
  drupal_json_output($settings);
}

